<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL4Mrmmh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL4Mrmmh/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerL4Mrmmh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerL4Mrmmh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerL4Mrmmh\App_KernelProdContainer([
    'container.build_hash' => 'L4Mrmmh',
    'container.build_id' => 'f568eb5a',
    'container.build_time' => 1629922394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL4Mrmmh');
