<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'partenaires' => [[], ['_controller' => 'App\\Controller\\PartenairesController::index'], [], [['text', '/partenaires']], [], []],
    'servicesapp_services_index' => [[], ['_controller' => 'App\\Controller\\ServicesController::index'], [], [['text', '/services/']], [], []],
    'servicesapp_services_internet' => [[], ['_controller' => 'App\\Controller\\ServicesController::internet'], [], [['text', '/services/internet']], [], []],
    'servicesapp_services_apndedier' => [[], ['_controller' => 'App\\Controller\\ServicesController::apndedier'], [], [['text', '/services/apndedier']], [], []],
    'servicesapp_services_intranet' => [[], ['_controller' => 'App\\Controller\\ServicesController::intranet'], [], [['text', '/services/intranet']], [], []],
    'servicesapp_services_mpls' => [[], ['_controller' => 'App\\Controller\\ServicesController::mpls'], [], [['text', '/services/mpls']], [], []],
    'servicesapp_services_pabx' => [[], ['_controller' => 'App\\Controller\\ServicesController::pabx'], [], [['text', '/services/pabx']], [], []],
    'servicesapp_services_vsat' => [[], ['_controller' => 'App\\Controller\\ServicesController::vsat'], [], [['text', '/services/vsat']], [], []],
    'servicesapp_services_drc' => [[], ['_controller' => 'App\\Controller\\ServicesController::drc'], [], [['text', '/services/drc']], [], []],
    'solutions' => [[], ['_controller' => 'App\\Controller\\SolutionsController::index'], [], [['text', '/solutions']], [], []],
];
