<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2bv1tPF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2bv1tPF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2bv1tPF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2bv1tPF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2bv1tPF\App_KernelDevDebugContainer([
    'container.build_hash' => '2bv1tPF',
    'container.build_id' => 'eee3de9e',
    'container.build_time' => 1629912415,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2bv1tPF');
