<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'partenaires' => [[], ['_controller' => 'App\\Controller\\PartenairesController::index'], [], [['text', '/partenaires']], [], []],
    'servicesapp_services_index' => [[], ['_controller' => 'App\\Controller\\ServicesController::index'], [], [['text', '/services/']], [], []],
    'servicesapp_services_internet' => [[], ['_controller' => 'App\\Controller\\ServicesController::internet'], [], [['text', '/services/internet']], [], []],
    'servicesapp_services_apndedier' => [[], ['_controller' => 'App\\Controller\\ServicesController::apndedier'], [], [['text', '/services/apndedier']], [], []],
    'servicesapp_services_intranet' => [[], ['_controller' => 'App\\Controller\\ServicesController::intranet'], [], [['text', '/services/intranet']], [], []],
    'servicesapp_services_mpls' => [[], ['_controller' => 'App\\Controller\\ServicesController::mpls'], [], [['text', '/services/mpls']], [], []],
    'servicesapp_services_pabx' => [[], ['_controller' => 'App\\Controller\\ServicesController::pabx'], [], [['text', '/services/pabx']], [], []],
    'servicesapp_services_vsat' => [[], ['_controller' => 'App\\Controller\\ServicesController::vsat'], [], [['text', '/services/vsat']], [], []],
    'servicesapp_services_drc' => [[], ['_controller' => 'App\\Controller\\ServicesController::drc'], [], [['text', '/services/drc']], [], []],
    'solutions' => [[], ['_controller' => 'App\\Controller\\SolutionsController::index'], [], [['text', '/solutions']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
